version: "3"
services:
  canvas:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - db-data:/var/lib/postgresql/9.3/main
    environment:
      - ACCOUNT_NAME
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
volumes:
  db-data:
